name: weather_forecast
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.19.0
  bloc: ^8.0.3
  get_it: ^7.6.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  http: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  freezed: ^2.3.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
